### PR TITLE
Increase test coverage, minor documentation fixes

### LINKED ISSUE #126: Increase coverage rate
The target value is >80%

### PR DESCRIPTION
**Pull request by edelarua**
Closes #126

### CODE REVIEW

File: tests/testthat.R [hunk 1]
```diff
@@ -0,0 +1,5 @@
+library(testthat)
+
+pkg_name <- "scda"
+library(pkg_name, character.only = TRUE)
```
Comment (Melkiades) [inline tests/testthat.R:4]: `"only" can weaken meaning` ahah I just found this funny. @cicdguy I remember a discussion about grammar checks, is there any update?

**Review by Melkiades — APPROVED** [review]
Lgtm! Thanks Emily :)))
